import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Inter } from "next/font/google";
// import Navbar from "./Component/Navbar/Navbar";
import ContexProvider from "./Context/ContexProvider";
import Footer from "./Component/Footer/Footer";
import { ToastContainer } from "react-toastify";
import Navbar from "./Component/Navbar/Navbar";


const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Project title here",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-slate-100 min-h-screen text-slate-900 flex flex-col`}>
        <ContexProvider>
      <Navbar></Navbar>
          <main className="flex-1">
            {children}
          </main>
        <Footer></Footer>
          </ContexProvider>
          
        
        <ToastContainer
        theme="dark"
        /> 
      </body>
    </html>
  );
}
